### ISSUE TITLE
[WEB] - Refactor Project

### ISSUE THREAD

**Issue by viniarruda** [react-shop/react-ecommerce#14]
The idea is refactor the project and the api to include better solutions and create a open source project to help people create a complete and easy e-commerce.

The e-commerce project it will be changed to: **(in construction)**

- [X] Monorepo
- [X] Design System
- [X] Storybook
- [X] SDK
- [ ] React with hooks
- [ ] Redux Hooks
- [ ] Redux-Saga
- [ ] Reselect
- [ ] Unit/Integration Tests

The Api will be changed to:

- Elixir
- Phoenix

## Future Features

- [ ] Home (List products)
- [ ] Detail products
- [ ] Recommended products
- [ ] Cart
- [ ] Checkout
- [ ] Login / Register
- [ ] Admin (Seller)
- [ ] Profile (Buyer)
- [ ] Contact Us
- [ ] Message between Seller and Buyer
- [ ] Ratings about the Seller
- [ ] Dashboard for Sellers
- [ ] Notifications
- [ ] Favorites
- [ ] Pwa
- [ ] Firebase or storage
- [ ] Socket.io
- [ ] App
- [ ] SSR

**Comment by MateusAndrade** [comment]
Using `reselector` for redux would be a great addition. I think that on some cases, we will need to save a lot of info at the store or make complex calculations, etc.

**Comment by viniarruda** [comment]
> Using [reslect](https://github.com/reduxjs/reselect) for redux would be a great addition. I think that on some cases, we will need to save a lot of info at the store or make complex calculations, etc.

Yes, I agree. Is very simple for create a selector for cart functions using reselect

**Comment by w3bdesign** [comment]
What about Context instead of Redux? Would save you from having to use Redux.

**Comment by viniarruda** [comment]
> What about Context instead of Redux? Would save you from having to use Redux.

Only context is very bad, because don't have a largest perfomance, but using Context + Hooks, is a good thing, because is very similar to redux implementation. I have a example here: https://github.com/viniarruda/spotify-project

My idea is use redux with hooks, and redux-saga to test the idea in a "largest" project, focusing in perfomance and tests, but we can use Context + hooks in native app, is a good idea too.

**Comment by lmeireles** [comment]
> > What about Context instead of Redux? Would save you from having to use Redux.
> 
> Only context is very bad, because don't have a largest performance, but using Context + Hooks, is a good thing, because is very similar to redux implementation. I have a example here: https://github.com/viniarruda/spotify-project
> 
> My idea is use redux with hooks, and redux-saga to test the idea in a "largest" project, focusing in perfomance and tests, but we can use Context + hooks in native app, is a good idea too.

I had some previous problems with the scalability of context with ReactNative. It seems that the slight lower performance of context API really shows up in low spec mobile devices.
Maybe context works well with simple applications with low traffic in the global state, at least that's what I got from my previous experiences.

**Comment by viniarruda** [comment]
> > > What about Context instead of Redux? Would save you from having to use Redux.
> > 
> > 
> > Only context is very bad, because don't have a largest performance, but using Context + Hooks, is a good thing, because is very similar to redux implementation. I have a example here: https://github.com/viniarruda/spotify-project
> > My idea is use redux with hooks, and redux-saga to test the idea in a "largest" project, focusing in perfomance and tests, but we can use Context + hooks in native app, is a good idea too.
> 
> I had some previous problems with the scalability of context with ReactNative. It seems that the slight lower performance of context API really shows up in low spec mobile devices.
> Maybe context works well with simple applications with low traffic in the global state, at least that's what I got from my previous experiences.

Hmm... how is a application for much users, I think the better option is use redux, but we can use context + hooks to test in web package. Don't have problem to change after too, is a open source project to test and feel free to open pr's after.

The idea is create a lot of components for design system first, after designer complet the design system. We have time to think before start the project.
