### ISSUE TITLE
How to fix errors?

### ISSUE THREAD

**Issue by f0f-fa** [react-shop/react-ecommerce#47]
When I launch 
`yarn start`
then show errors:
`yarn run v1.22.4
$ lerna run start --parallel --scope '{web,@react-shop/design-system,@react-shop/sdk}'
lerna notice cli v3.19.0
lerna notice filter including "{web,@react-shop/design-system,@react-shop/sdk}"
lerna info filter [ '{web,@react-shop/design-system,@react-shop/sdk}' ]
lerna info Executing command in 3 packages: "yarn run start"
web: $ react-scripts start
@react-shop/design-system: $ tsc && tsc --build tsconfig.esm.json -w
@react-shop/sdk: $ tsc && tsc --build tsconfig.esm.json -w
web: Starting the development server...
web: events.js:292
web:       throw er; // Unhandled 'error' event
web:       ^
web: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/lt/Apps/react-ecommerce-master/packages/web/public'
web:     at FSWatcher.<computed> (internal/fs/watchers.js:169:26)
web:     at Object.watch (fs.js:1388:34)
web:     at createFsWatchInstance (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:38:15)
web:     at setFsWatchListener (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:81:15)
web:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:233:14)
web:     at FSWatcher.NodeFsHandler._handleDir (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:429:19)
web:     at FSWatcher.<anonymous> (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:477:19)
web:     at FSWatcher.<anonymous> (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:482:16)
web:     at FSReqCallback.oncomplete (fs.js:172:5)
web: Emitted 'error' event on FSWatcher instance at:
web:     at FSWatcher._handleError (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/index.js:260:10)
web:     at createFsWatchInstance (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:40:5)
web:     at setFsWatchListener (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:81:15)
web:     [... lines matching original stack trace ...]
web:     at FSReqCallback.oncomplete (fs.js:172:5) {
web:   errno: -28,
web:   syscall: 'watch',
web:   code: 'ENOSPC',
web:   path: '/home/lt/Apps/react-ecommerce-master/packages/web/public',
web:   filename: '/home/lt/Apps/react-ecommerce-master/packages/web/public'
web: }
web: error Command failed with exit code 1.
web: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in 'web'
lerna ERR! yarn run start stdout:
$ react-scripts start
Starting the development server...

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run start stderr:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/lt/Apps/react-ecommerce-master/packages/web/public'
    at FSWatcher.<computed> (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1388:34)
    at createFsWatchInstance (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (fs.js:172:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/lt/Apps/react-ecommerce-master/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:172:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/lt/Apps/react-ecommerce-master/packages/web/public',
  filename: '/home/lt/Apps/react-ecommerce-master/packages/web/public'
}
error Command failed with exit code 1.

lerna ERR! yarn run start exited 1 in 'web'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

How to fix it? And how to launch app on android and ios? there is no description In README about it.

**Comment by viniarruda** [comment]
Hmm, this is new for me. Let me try play this error here.

And about the app, I decided to remove the app because have a lot of problems using rn inside of monorepo. The idea is configure web 100% functional and after try configure app again or pass to other repo.

Unfortanelly React Native have a lot of problems to understand the mono repo folder because of the bundle

**Comment by viniarruda** [comment]
Here is running normally. I just push a adjust of required props.

_________________________________________________________________________________

It’s hitting your system's file watchers limit

Try echo `fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Read more about what’s happening at guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

_________________________________________________________________________________

Following this issue: https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756

**Comment by f0f-fa** [comment]
Thank you very much!
